---
apiVersion: opensearch.stackable.tech/v1alpha1
kind: OpenSearchCluster
metadata:
  name: simple-opensearch
spec:
  image:
    productVersion: 3.4.0
  clusterConfig:
    security:
      settings:
        config:
          managedBy: API
          content:
            value:
              _meta:
                type: config
                config_version: 2
              config:
                dynamic:
                  authc:
                    basic_internal_auth_domain:
                      description: Authenticate via HTTP Basic against internal users database
                      http_enabled: true
                      transport_enabled: true
                      order: 1
                      http_authenticator:
                        type: basic
                        challenge: true
                      authentication_backend:
                        type: intern
                  authz: {}
        internalUsers:
          managedBy: API
          content:
            valueFrom:
              secretKeyRef:
                name: initial-opensearch-security-config
                key: internal_users.yml
        rolesMapping:
          managedBy: API
          content:
            valueFrom:
              secretKeyRef:
                name: initial-opensearch-security-config
                key: roles_mapping.yml
  nodes:
    roleConfig:
      discoveryServiceListenerClass: external-stable
    roleGroups:
      default:
        replicas: 3
    configOverrides:
      opensearch.yml:
        plugins.security.restapi.roles_enabled: all_access
