---
apiVersion: opensearch.stackable.tech/v1alpha1
kind: OpenSearchCluster
metadata:
  name: simple-opensearch
spec:
  image:
    productVersion: 3.4.0
  nodes:
    roleConfig:
      discoveryServiceListenerClass: external-stable
    roleGroups:
      default:
        replicas: 3
    configOverrides:
      opensearch.yml:
        plugins.security.allow_default_init_securityindex: "true"
        plugins.security.restapi.roles_enabled: all_access
    podOverrides:
      spec:
        containers:
          - name: opensearch
            volumeMounts:
              - name: security-config
                mountPath: /stackable/opensearch/config/opensearch-security
                readOnly: true
        volumes:
          - name: security-config
            secret:
              secretName: opensearch-security-config
              defaultMode: 0o660
